add audiobookshelf install sh
swizzin/swizzin pull request #1028
Opened 2023-06-14 15:52 UTC by lupu60

Add installation for audiobookshelf

## Description
Add installation for audiobookshelf

## Change Categories
- New feature 

## Checklist

- [ ] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [ ] Docs have been made OR are not necessary
    - PR link: 
- [ ] Changes to panel have been made OR are not necessary
    - PR link: 
- [ ] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [ ] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [ ] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [ ] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Testing was done
   - [ ] Tests created or no new tests necessary
   - [ ] Tests executed

## Test scenarios

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Jammy 		|			|			|			|				|
| Focal 		|			|			|			|				|
| Bionic		|			|			|			|				|
| Bullseye		|			|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### ✅❎ Passed

### 🛠🛠 TODO

### ❌❌ Currently failing

2023-06-14 16:55 UTC, liaralabs commented
Thanks for the contribution lupu60. I have a few items of feedback:

- At the moment we are requiring contributors of new applications to be willing to maintain these applications long term. The core maintainers are already stretched thin with maintaining the existing packages. Are you willing to commit to this?
- The package is missing nginx proxy configs
- Dashboard integration: You should submit a PR to the swizzin_dashboard repository to make this changes there rather than echoing these changes into the profiles. The method you have chosen is not guaranteed to not be clobbered during box updates

2023-06-15 14:04 UTC, lupu60 commented
> 

Hello @liaralabs.
* I can handle audiobookshelf and I'm sure others will join after will be available.
* I need to investigate the nginx config, looks like there is an issue:
   https://github.com/advplyr/audiobookshelf/issues/385
* I will adapt the pr and open a new one in the swizzin_dashboard

2023-07-17 10:17 UTC, flying-sausages requested changes
Mostly what Liara said, let me know if there's anything I can help you with!

2023-07-17 10:17 UTC, flying-sausages commented on scripts/install/audiobookshelf.sh
> +}
Could you remove this and make a PR on the panel repo please? Let me know if you need help in the discord

2023-07-17 10:17 UTC, flying-sausages commented on scripts/install/audiobookshelf.sh
> +    echo_progress_start "Installing audiobookshelf apt sources"
`echo_progress_start` kind of expects an `echo_progress_done`, think of the two as the slices of bread in a waiting sandwich

2023-07-17 10:17 UTC, flying-sausages commented on scripts/install/audiobookshelf.sh
> +    apt install gnupg curl
We have `apt_install` defined which helps handle these without the interactivity

2023-07-17 10:17 UTC, flying-sausages commented on scripts/install/audiobookshelf.sh
> +    apt install audiobookshelf
Same as above, would be nice to keep the apt installs to one call with one big list in my opinion

2023-07-17 10:17 UTC, flying-sausages commented on scripts/install/audiobookshelf.sh
> +    apt install gnupg curl
You can use it like this, it is imported into the environment anytime you run `box`, you can check `sources/globals.sh` to see what else there is
```suggestion
    apt_install gnupg curl
```

2023-07-17 10:17 UTC, flying-sausages commented on scripts/remove/audiobookshelf.sh
> +}
Again, not really needed if it's in the panel repo

2023-07-17 10:17 UTC, flying-sausages commented on scripts/remove/audiobookshelf.sh
> +    apt autoremove
We've got apt functions for these two, but I don't think you need to do the update here, just takes time. The apt tools will auto-update themselves as they're being called if necessary

2023-07-17 10:17 UTC, flying-sausages commented on scripts/remove/audiobookshelf.sh
> +    sysctl disable audiobookshelf.service
`disable` also takes `--now` parameter so you can get these done in one line. Would also be nice to pass the `-q` flag so it's quiet

2023-08-18 07:56 UTC, closed without merging

2025-02-03 14:27 UTC, ligix commented
> At the moment we are requiring contributors of new applications to be willing to maintain these applications long term. The core maintainers are already stretched thin with maintaining the existing packages. Are you willing to commit to this?

I would but sadly ABS uses the header `Authorization` which prevents the browser from sending the basic auth credentials. This, for obvious reasons, breaks swizzin and the only workaround appears to disable authorization altogether.

For anyone wandering over from google this works:

/etc/nginx/apps/audiobookself.conf
```
location /abs {
    return 301 /audiobookshelf/;
}

location /audiobookshelf/ {
    proxy_pass              http://127.0.0.1:13378;
    proxy_http_version      1.1;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header Host               $http_host;
    proxy_set_header Upgrade            $http_upgrade;
    proxy_set_header Connection         "upgrade";
    proxy_set_header        X-Forwarded-Host        $http_host;
    proxy_redirect                      http:// https://;
    client_max_body_size                10240M;
}
```