fix(prowlarr): simplify breaking nginx config
swizzin/swizzin pull request #763
Opened 2021-08-29 17:30 UTC by flying-sausages

## Description
Simplifies prowlarr nginx config

## Fixes issues: 
<img width="984" alt="afbeelding" src="https://user-images.githubusercontent.com/23618693/131259617-27cdbc14-ce38-4a88-b66a-376cde10bca5.png">
🤷 

## Proposed Changes:
Couldn't reproduce the issue, but it wouldn't hurt to simplify the config down anyway

## Change Categories

- Bug fix 
## Checklist

- [x] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [x] Docs have been made OR are not necessary
    - PR link: 
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] Testing was done
   - [ ] Tests created or no new tests necessary
   - [ ] Tests executed

## Test scenarios

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Focal 		|			|			|			|				|
| Bionic		|			|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### ✅❎ Passed

### 🛠🛠 TODO

### ❌❌ Currently failing

2021-08-29 21:45 UTC, bakerboy448 commented
tested the new nginx; does not work at all

the below DOES work
```
location /prowlarr {
  proxy_pass        http://127.0.0.1:9696/prowlarr;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto https;
  proxy_redirect off;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
}

  location /prowlarr/api { auth_request off;
  proxy_pass       http://127.0.0.1:9696/prowlarr/api;
}

  location ~ /prowlarr/[0-9]+/api { auth_request off;
  proxy_pass       http://127.0.0.1:9696;
}

  location /prowlarr/Content { auth_request off;
    proxy_pass http://127.0.0.1:9696/prowlarr/Content;
 }
```
 https://wiki.servarr.com/prowlarr/installation#nginx

2021-11-15 23:14 UTC, bakerboy448 commented
will this be merged anytime soon to stop providing users with bad installs?
@brettpetch ?

2021-11-15 23:14 UTC, bakerboy448 commented on scripts/nginx/prowlarr.sh
> +    proxy_set_header    Host                \$proxy_host;
this needs to be $host

2021-11-15 23:17 UTC, bakerboy448 commented
https://github.com/swizzin/swizzin/issues/796

2021-11-15 23:19 UTC, bakerboy448 commented on scripts/nginx/prowlarr.sh
> +    proxy_set_header    X-Forwarded-Proto   \$scheme;
missing header
`  proxy_set_header X-Forwarded-Host  $host;`

2021-11-15 23:20 UTC, bakerboy448 requested changes
see comments; the conf is still wrong and not what FS was told to change it to.

2022-04-13 00:56 UTC, brettpetch approved these changes

2022-04-13 00:57 UTC, brettpetch commented
@bakerboy448 can you please confirm that this is up to date? If so I'll merge into develop ;b

2022-04-13 00:59 UTC, bakerboy448 commented on scripts/nginx/prowlarr.sh
> +# Allow Content
Can be removed

2022-04-13 00:59 UTC, bakerboy448 commented on scripts/nginx/prowlarr.sh
> +    proxy_pass      http://127.0.0.1:$app_port/$app_baseurl/api;
This can just be IP:Port, no?

Compare to SWAGs confs

2022-05-21 16:29 UTC, liaralabs commented
Can this get closed as part of the recent *arr nginx proxy PR?

2022-05-21 16:32 UTC, closed without merging